stages:
  - lint
  - build
  - deploy

lint:
  image: node:14-alpine
  stage: lint
  allow_failure: true
  script:
    - npm run lint

check-types:
  image: node:14-alpine
  stage: lint
  script:
    - npm install
    - npm run check-types

build:
  image: node:14-alpine
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  image: node:14-slim
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - echo $SSH_PRIVATE_KEY | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete
      --exclude-from '.gitignore'
      --exclude '.gitignore'
      --exclude '.git'
      ./build/* deploy@35.223.84.150:~/realworld
