stages:
  - lint
  - build
  - deploy

image: node:14-alpine

lint:
  stage: lint
  allow_failure: true
  script:
    - npm run lint

check-types:
  stage: lint
  script:
    - npm install
    - npm run check-types

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next

deploy:
  stage: deploy
  script:
    - apk --update add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo $SSH_PRIVATE_KEY | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete
      --exclude-from '.gitignore'
      --exclude '.gitignore'
      --exclude '.git'
      ./.next/* deploy@35.223.84.150:~/realworld
