stages:
  - lint

lint:
  image: node:14-alpine
  stage: lint
  allow_failure: true
  script:
    - npm run lint

check-types:
  image: node:14-alpine
  stage: lint
  script:
    - npm install
    - npm run check-types