name: "deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:14-alpine

    steps:
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: |
          npm ci
          NEXT_PUBLIC_HOST=http://$HOST:3000 NEXT_PUBLIC_FRONTEND_VERSION=${"$CI_COMMIT_SHORT_SHA:0:8"} npm run build
        env:
          HOST: ${{ secrets.HOST }}
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: .next
