name: "lint"

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: node:14-alpine

    steps:
      - uses: actions/checkout@v2
      - name: "Check if files are formatted with prettier"
        run: |
          npm run lint
      - name: "Check types"
        run: |
          npm install --no-save typescript
          npm run check-types
