name: "lint"

on:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    container:
      image: node:14-alpine

    steps:
      - uses: actions/checkout@v2
      - name: "prettier"
        run: |
          npm run lint
